pm-catch.rb:3
def zero_div
# # ***************************************************
# # Test catch
# # ***************************************************
# set debuggertesting on
Currently testing the debugger is on.
# set autoeval off
autoeval is off.
# set basename on
basename is on.
# info catch
No exceptions set to be caught.
# catch ZeroDivisionError off
*** Catch for exception ZeroDivisionError not found.
# catch ZeroDivisionError off afdasdf
*** Unknown command: "catch ZeroDivisionError off afdasdf".  Try "help".
# catch ZeroDivisionError
Catch exception ZeroDivisionError.
# info catch
ZeroDivisionError
# catch ZeroDivisionError off
Catch for exception ZeroDivisionError removed.
# info catch
No exceptions set to be caught.
# catch ZeroDivisionError
Catch exception ZeroDivisionError.
# c
Catchpoint at pm-catch.rb:5: `divided by 0' (ZeroDivisionError)
	from ../rdbg.rb:23:in `runner'
	from ../rdbg.rb:32:in `<main>'
pm-catch.rb:5
1/0
# where
--> #0 Object.zero_div at line pm-catch.rb:5
    #1 at line pm-catch.rb:9
# jump 6
pm-catch.rb:6
x = 6
# cont
6
	./pm-catch.rb:10:in `<top (required)>'
	tdebug.rb:61:in `debug_load'
	tdebug.rb:61:in `debug_program'
	tdebug.rb:252:in `<top (required)>'
	../rdbg.rb:23:in `load'
	../rdbg.rb:23:in `runner'
	../rdbg.rb:32:in `<main>'
Uncaught exception: RuntimeError
